# src/state.py
from typing import TypedDict, List, Dict, Any, Annotated
import operator

class AgentState(TypedDict):
    # 1. The original entry query from the user
    user_query: str
    
    # 2. Array of sub-questions generated by the Planner Agent
    sub_questions: List[str]
    
    # 3. Accumulated research context. 
    # Annotated[..., operator.add] ensures data appends together instead of overwriting!
    research_data: Annotated[List[Dict[str, Any]], operator.add]
    
    # 4. Verified and grounded claims from the Fact-Checker
    vetted_facts: List[Dict[str, Any]]
    
    # 5. The final beautifully generated markdown output
    final_report: str